index/urls.py
from django.urls import path

from . import views

app_name = "index"

urlpatterns = [
    path('', views.index, name='index'),
    path('kitapligi-genislet/', views.ekle, name="ekle")
]

kitaplik/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("index.urls"))
]

index/models.py
from django.db import models

# Create your models here.

class Kitap(models.Model): 

    title = models.CharField(max_length=2000)
    author = models.CharField(max_length=1000, default=None, blank=True, null=True)
    file = models.FileField(default=None,blank=True, null=True, upload_to="book_files/")
    text = models.TextField(max_length=9999999, default=None, blank=True, null=True)
    score = models.CharField(max_length=40, null=True, blank=True)

    class Meta:
        verbose_name = 'Kitap'
        verbose_name_plural = 'Kitaplar'

    def __str__(self): 
        return self.title

index/forms.py
from django.forms import ModelForm
from .models import Kitap

from django.forms import ModelForm, TextInput, FileInput

class KitapForm(ModelForm):
    class Meta:
        model = Kitap
        fields = ['title', 'author', 'file']
        widgets = {
            'title': TextInput(attrs={
                'class': "form-control",
                'id': 'book_name_input',
                'style': 'max-width: 300px;',
                'placeholder': 'Kitap ismi',
                'required': True,
            }),
                'author': TextInput(attrs={
                'class': "form-control",
                'id': 'author_name_input',
                'style': 'max-width: 300px;',
                'placeholder': 'Yazar ismi',
                'required': False,
            }),
                'file': FileInput(attrs={
                'class': "form-control", 
                'id': 'book_file_input',
                'style': 'max-width: 300px;',
                'placeholder': 'Dosya',
                'required': True,
            })
        }

index/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.files.storage import default_storage

from .forms import KitapForm
from .models import Kitap
from .algo import get_book_data, scale_data, predict_suitability
import os
from pdftextract import XPdf
import random

# Create your views here.

def index(request): 
    kitaplar = Kitap.objects.filter(score__isnull=False)
    
    positive = "btn-outline-success" 
    negative = "btn-outline-danger"

    
    if request.method == "POST":
        if "search" in request.POST:
            print("search")
            isim = request.POST["search"]   
            kitaplar = Kitap.objects.filter(title__icontains=isim)
        elif "positive" in request.POST: 
            print("positive")
            kitaplar = Kitap.objects.filter(score__gte=0.5)
            positive = "btn-success"
            negative = "btn-outline-danger"
        elif "negative" in request.POST: 
            print("negative")
            kitaplar = Kitap.objects.filter(score__lte=0.5)
            positive = "btn-outline-success"
            negative = "btn-danger"
        elif "lang" in request.POST: 
            request.session["lang"] = "en"
            return render(request, "index/eng_index.html", {"kitaplar": kitaplar, "positive": positive, "negative": negative})
        elif "dil" in request.POST: 
            request.session["lang"] = "tr"
            return render(request, "index/index.html", {"kitaplar": kitaplar, "positive": positive, "negative": negative})
        print("results::")
        print(request.POST)
    
    lang = request.session.get("lang")

    if lang == "tr": 
        return render(request, "index/index.html", {"kitaplar": kitaplar, "positive": positive, "negative": negative})
    elif lang == "en": 
        return render(request, "index/eng_index.html", {"kitaplar": kitaplar, "positive": positive, "negative": negative})


    return render(request, "index/index.html", {"kitaplar": kitaplar, "positive": positive, "negative": negative})


def ekle(request): 


    if request.method == 'POST':
        form = KitapForm(request.POST, request.FILES)

        if  "lang" in request.POST: 
            request.session["lang"] = "en"
            return render(request, "index/eng_ekle.html", {'form': form})
        elif "dil" in request.POST: 
            request.session["lang"] = "tr"
            return render(request, "index/ekle.html", {'form': form})


        if form.is_valid():
            # file is saved
            form.save()

            
            book_file = request.FILES["file"]
            BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            special_characters = ".:,;~-_[]()=@?\/}{&%$#^'*!£+\"><|\""
            full_path=os.path.join(BASE_DIR, "book_files/"+book_file.name.replace(" ", "_").replace("(", "").replace(")", "").replace("'", "").replace(",", ""))
            print(full_path)


            try: 
                f = open(full_path, 'r', encoding="utf8")
                text = f.read()
                f.close()
            except TypeError: 
                text = XPdf(full_path).to_text()
            except UnicodeDecodeError: 
                text = XPdf(full_path).to_text()


            k = Kitap.objects.filter(title=request.POST["title"])
            k.update(text=text)

            # os.remove(full_path)

            book_data = get_book_data(text=text, book_location=None)
            scaled_book_data = scale_data(book_data)
            suitability = predict_suitability(scaled_book_data)

            k.update(score=suitability)


            return redirect("index:index")
    else:
        form = KitapForm()


    lang = request.session.get("lang")

    if lang == "en": 
        return render(request, "index/eng_ekle.html", {'form': form})

    return render(request, "index/ekle.html", {'form': form})

templates/_base.html
<!DOCTYPE html>
<html lang="en"> 
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="Alp Niksarli">
  <meta name="keywords" content="Tubitak, kitaplık">

	<title>{% block title %} Kitaplık+ {% endblock %}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js" integrity="sha512-Tn2m0TIpgVyTzzvmxLNuqbSJH3JP8jm+Cy3hvHrW7ndTDcJ1w5mBiksqDBb8GpE2ksktFvDB/ykZ0mDpsZj20w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/fontawesome.css" integrity="sha384-eHoocPgXsiuZh+Yy6+7DsKAerLXyJmu2Hadh4QYyt+8v86geixVYwFqUvMU8X90l" crossorigin="anonymous"/>
  {% load static %}
  <link rel="stylesheet" href="{% static 'base.css' %}"> 
  {% block css %} {% endblock %}
</head>
<body>

<nav id="navbar" class="navbar navbar-expand-md fixed-top">
  <a class="navbar-brand" style="color:#35a0de !important" href="{% url 'index:index' %}">Kitaplık+</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon">
      <i class="fas fa-bars" style="color:#35a0de; font-size:24px;"></i>
    </span> 
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item navigate">
        <a id="nav-about" class="nav-link" href="{% url 'index:ekle' %}">Kitaplığı Genişlet</a>
      </li>
    </ul>
    <div class="my-2 my-lg-0 col-md-6 d-flex justify-content-end">
      <form method="POST" class="form-inline suitability-form">
        {% csrf_token %}
        <input type="hidden" name="positive" value="positive">
        <button type="submit" class="btn {{positive}} mr-2 positive-button" onclick="getPositives">Uygun</button>
      </form>
      <form method="POST" class="form-inline suitability-form">
        {% csrf_token %}
        <input type="hidden" name="negative" value="negative">
        <button type="submit" class="btn {{negative}} mr-3 negative-button" onclick="getNegatives">Uygunsuz</button>
      </form>
      <form method="POST" class="form-inline">
        {% csrf_token %}
        <input type="hidden" name="lang" value="lang">
        <button type="submit" class="btn btn-primary">EN</button>
      </form>
      </div>
  </div>
</nav>

{% block content%}{% endblock %}


  <footer class="footer navbar text-center">
    <div class="container">
      <span>© 2023 <a href="">Kitaplık+</a>. 2204-A TÜBİTAK projesi için <a href="">Alp Niksarlı</a>, <a href="">Sadık Ozan Görgü</a> ve <a href="">Ege Gençer</a> tarafından geliştirildi.</span>
    </div>
  </footer>

</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  
  <script src="{% static 'script.js' %}">
  </script>
  <script>

    var skorSpans = document.querySelectorAll("span.skor"); 

    skorSpans.forEach(skorSpan => {
      var skorVal = parseFloat(skorSpan.innerHTML); 
      console.log(skorSpan.innerHTML);
      if (skorVal > 0.50) {
        var color = "green";
      } else {
        var color = "red";
      }
      skorRow = skorSpan.parentElement;
      skorRow.classList.add(color);  
    })
    var positiveBtn = document.querySelector(".positive-button"); 
    var negativeBtn = document.querySelector(".negative-button");

    function getPositives(e) {
      e.preventDefault(); 
      positiveBtn.classList.remove("btn-outline-success"); 
      positiveBtn.classList.add("btn-success"); 

      negativeBtn.classList.remove("btn-danger"); 
      negativeBtn.classList.add("btn-outline-danger"); 
    }

    function getNegative(e) {
      e.preventDefault();
      negativeBtn.classList.remove("btn-outline-danger"); 
      negativeBtn.classList.add("btn-danger"); 

      positiveBtn.classList.remove("btn-success"); 
      positiveBtn.classList.add("btn-outline-success"); 
    }

  </script>
</html>

templates/eng_base.html
<!DOCTYPE html>
<html lang="en"> 
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="Alp Niksarli">
  <meta name="keywords" content="Tubitak, kitaplık">

	<title>{% block title %} Kitaplık+ {% endblock %}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js" integrity="sha512-Tn2m0TIpgVyTzzvmxLNuqbSJH3JP8jm+Cy3hvHrW7ndTDcJ1w5mBiksqDBb8GpE2ksktFvDB/ykZ0mDpsZj20w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/fontawesome.css" integrity="sha384-eHoocPgXsiuZh+Yy6+7DsKAerLXyJmu2Hadh4QYyt+8v86geixVYwFqUvMU8X90l" crossorigin="anonymous"/>
  {% load static %}
  <link rel="stylesheet" href="{% static 'base.css' %}"> 
  {% block css %} {% endblock %}
</head>
<body>

<nav id="navbar" class="navbar navbar-expand-md fixed-top">
  <a class="navbar-brand" style="color:#35a0de !important" href="{% url 'index:index' %}">Kitaplık+</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon">
      <i class="fas fa-bars" style="color:#35a0de; font-size:24px;"></i>
    </span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item navigate">
        <a id="nav-about" class="nav-link" href="{% url 'index:ekle' %}">Enhance the Library</a>
      </li>
    </ul>
    <div class="my-2 my-lg-0 col-md-6 d-flex justify-content-end">
      <form method="POST" class="form-inline suitability-form">
        {% csrf_token %}
        <input type="hidden" name="positive" value="positive">
        <button type="submit" class="btn btn-outline-success mr-2">Suitable</button>
      </form>
      <form method="POST" class="form-inline suitability-form">
        {% csrf_token %}
        <input type="hidden" name="negative" value="negative">
        <button type="submit" class="btn btn-outline-danger mr-3">Not Suitable</button>
      </form>
      <form method="POST" class="form-inline">
        {% csrf_token %}
        <input type="hidden" name="dil" value="dil">
        <button type="submit" class="btn btn-primary">TR</button>
      </form>
      </div>
  </div>
</nav>

{% block content%}{% endblock %}


  <footer class="footer navbar text-center">
    <div class="container">
      <span>© 2023 <a href="">Kitaplık+</a>. Developed by <a href="">Alp Niksarli</a>, <a href="">Sadık Ozan Görgü</a> ve <a href="">Ege Gençer</a> for our 2204-A TUBITAK project.</span>
    </div>
  </footer>

</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  
  <script src="{% static 'script.js' %}">
  </script>
  <script>

    var skorSpans = document.querySelectorAll("span.skor"); 

    skorSpans.forEach(skorSpan => {
      var skorVal = parseFloat(skorSpan.innerHTML); 
      console.log(skorSpan.innerHTML);
      if (skorVal > 0.50) {
        var color = "green";
      } else {
        var color = "red";
      }
      skorRow = skorSpan.parentElement;
      skorRow.classList.add(color);  
    })

  </script>
</html>

templates/index/ekle.html
{% extends '_base.html' %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'loading-animation.css' %}">
{% endblock %}

{% block content %}
<h1 class="display-4 mt-3 mb-3 text-center">Kitaplık+</h1>

<main role="main" class="container d-flex justify-content-center">
    <form class="form-signin container" method="POST" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Kitap ekleyiniz</h1>
        <!-- <label for="isim" class="sr-only">Email adresi</label>
        <input name="isim" type="email" id="isim" class="form-control mb-2" placeholder="Kitap ismi" required autofocus>
        <label for="kitap" class="sr-only">Şifre</label>
        <input name="kitap" type="file" id="kitap" class="form-control mb-2" required> -->
        <div class="row mb-3">
            {% for field in form  %}
              <div class="col-sm-4">
               {{ field }} 
              </div>
            {% endfor %}
        </div>  

        <div class="form-group">
            <button id="submitBtn" class="btn btn-lg btn-primary btn-block" type="submit">Kitabı ekle</button>
        </div>
    </form>

    <div class="book">
        <div class="inner">
            <div class="left"></div>
            <div class="middle"></div>
            <div class="right"></div>
        </div>
        <ul>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </div>
</main>

<script>
    var suitabilityForms = document.querySelectorAll(".suitability-form");
    suitabilityForms.forEach((form) => {
        form.hidden = true;
        console.log(form);
    })

    var bookFileInput = document.querySelector("#book_file_input");

    bookFileInput.placeholder='Kitap dosyası seçilmedi';


    // put loading animation 
    var submitBtn = document.querySelector("#submitBtn");
    var loadingAnimation = document.querySelector(".book");
    var inputs = document.querySelectorAll("input"); 

    // doument.querySelector("#book_name_input").required = true;
    // doument.querySelector("#book_file_input").required = true;
    const isEmpty = (str) => (!str?.length);

    submitBtn.addEventListener("click", e => {
        var bookName = document.querySelector("#book_name_input").value
        var fileInput = document.querySelector("#book_file_input").value

        if (!isEmpty(bookName) & !isEmpty(fileInput)) {
            loadingAnimation.style.display = "block";  
            inputs.forEach(input => {
                input.readOnly = true;
            })

            setTimeout(function() {
                console.log("function working..."); 
                document.querySelector("#book_file_input").disabled = true;
                submitBtn.disabled = true;     
            }, 3)
            
            submitBtn.innerHTML = "Kitabınız ekleniyor...";
        }
    }) 


</script>

{% endblock %}

templates/index/eng_ekle.html
{% extends 'eng_base.html' %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'loading-animation.css' %}">
{% endblock %}

{% block content %}
<h1 class="display-4 mt-3 mb-3 text-center">Kitaplık+</h1>

<main role="main" class="container d-flex justify-content-center">
    <form class="form-signin container" method="POST" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Add a book</h1>
        <!-- <label for="isim" class="sr-only">Email adresi</label>
        <input name="isim" type="email" id="isim" class="form-control mb-2" placeholder="Kitap ismi" required autofocus>
        <label for="kitap" class="sr-only">Şifre</label>
        <input name="kitap" type="file" id="kitap" class="form-control mb-2" required> -->
        <div class="row mb-3">
            {% for field in form  %}
              <div class="col-sm-4">
               {{ field }} 
              </div>
            {% endfor %}
        </div>  

        <div class="form-group">
            <button id="submitBtn" class="btn btn-lg btn-primary btn-block" type="submit">Add Book</button>
        </div>
    </form>


    <div class="book">
        <div class="inner">
            <div class="left"></div>
            <div class="middle"></div>
            <div class="right"></div>
        </div>
        <ul>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </div>
</main>

<script>
    var suitabilityForms = document.querySelectorAll(".suitability-form");
    suitabilityForms.forEach((form) => {
        form.hidden = true;
        console.log(form);
    })

    var bookNameInput = document.querySelector("#book_name_input");
    var authorNameInput = document.querySelector("#author_name_input");

    bookNameInput.placeholder='Book name';
    authorNameInput.placeholder='Author name';

    // put loading animation 
    var submitBtn = document.querySelector("#submitBtn");
    var loadingAnimation = document.querySelector(".book");
    var inputs = document.querySelectorAll("input"); 

    // doument.querySelector("#book_name_input").required = true;
    // doument.querySelector("#book_file_input").required = true;
    const isEmpty = (str) => (!str?.length);


    submitBtn.addEventListener("click", e => {
        var bookName = document.querySelector("#book_name_input").value
        var fileInput = document.querySelector("#book_file_input").value

        if (!isEmpty(bookName) & !isEmpty(fileInput)) {
            loadingAnimation.style.display = "block";  
            inputs.forEach(input => {
                input.readOnly = true;
            })

            setTimeout(function() {
                console.log("function working..."); 
                document.querySelector("#book_file_input").disabled = true;
                submitBtn.disabled = true;     
            }, 100)
            
            submitBtn.innerHTML = "Kitabınız ekleniyor...";
        }
    })


</script>

{% endblock %}

templates/index/eng_index.html
{% extends 'eng_base.html' %}

{% block css %}

<style>
    .green {
        color: green;
    }
    
    .red {
        color: red;
    }
    
    .orange {
        color: orange;
    }    
</style>

{% endblock %}

{% block content %}
<h1 class="display-4 mt-3 mb-2 text-center">Kitaplık+</h1>
<p class="mb-3 text-center font-italic">More than a library</p>
<main role="main" class="container d-flex flex-column justify-content-center">
    <div class="formdiv d-flex flex-column justify-content-center mb-3">
        <form method="POST" style="width: 100% !important" class="form-inline my-2 my-lg-0 d-flex justify-content-center mb-3 mt-6">
            {% csrf_token %}
            <div style="position: relative;">
                <input name="search"  class="custom_search form-control mr-sm-2" type="search" placeholder="Search..." aria-label="Search">
                <span class="search_span"></span>
            </div>
            <button class="ml-lg-3 btn btn-success my-2 my-sm-0 search_button tx--white" type="submit" ripple="ripple">Find</button>
        </form>
    </div>
    <div class="kitaplar d-flex flex-column align-items-center justify-content-start mt-6">
        {% for kitap in kitaplar %}
           <p class="kitap-row"><b>Name:</b> {{kitap.title}} &emsp; <b>Score:</b> <span class="skor">{{kitap.score|floatformat:3}}</span></p>
        {% empty %}
            <p>No available books..</p>
        {% endfor %}
    </div>
</main>

{% endblock %}

templates/index/index.html
{% extends '_base.html' %}

{% block css %}

<style>
    .green {
        color: green;
    }
    
    .red {
        color: red;
    }
    
    .orange {
        color: orange;
    }    
</style>

{% endblock %}

{% block content %}
<h1 class="display-4 mt-3 mb-2 text-center">Kitaplık+</h1>
<p class="mb-3 text-center font-italic">Bir kitap da sen koy</p>
<main role="main" class="container d-flex flex-column justify-content-center">
    <div class="formdiv d-flex flex-column justify-content-center mb-3">
        <form method="POST" style="width: 100% !important" class="form-inline my-2 my-lg-0 d-flex justify-content-center mb-3 mt-6">
            {% csrf_token %}
            <div style="position: relative;">
                <input name="search"  class="custom_search form-control mr-sm-2" type="search" placeholder="Ara..." aria-label="Search">
                <span class="search_span"></span>
            </div>
            <button class="ml-lg-3 btn btn-success my-2 my-sm-0 search_button tx--white" type="submit" ripple="ripple">Başlat</button>
        </form>
    </div>
    <div class="kitaplar d-flex flex-column align-items-center justify-content-start mt-6">
        {% for kitap in kitaplar %}
           <p class="kitap-row"><b>İsim:</b> {{kitap.title}} &emsp; <b>Skor:</b> <span class="skor">{{kitap.score|floatformat:3}}</span></p>
        {% empty %}
            <p>Kitap bulunamadı..</p>
        {% endfor %}
    </div>
</main>

{% endblock %}